FROM node:22-alpine

WORKDIR /app


COPY package.json package-lock.json* ./
RUN \
  if [ -f package-lock.json ]; then npm ci; \
  fi

RUN npm install

COPY . .

COPY .env .env
RUN npm run build

ENV NODE_ENV=production

CMD ["npm", "run", "start:dev"]
